### ISSUE TITLE
[bug] no response headers in webui

### ISSUE THREAD

**Issue by jathek** [LizardByte/Sunshine#1186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Sunshine does not send any HTTP response headers. When I try to proxy it behind my domain using traefik's TCP routing, the page gets served as raw HTML text, not a rendered page. I think maybe response headers would fix this? Specifically `content-type: text/html; charset=utf-8` is what my guess would be for the bare minimum fix, although I don't know what other headers should be returned as a best practice.

### Expected Behavior

Proxying behind traefik should result in the normal webui instead of raw text.

### Additional Context

<details>
<summary>traefik config</summary>

```yml
tcp:
  routers:
    sunshine-rtr:
      rule: "HostSNI(`sunshine.MYDOMAIN.com`)" 
      entryPoints:
        - websecure
      service: sunshine-svc
      tls:
        passthrough: true
  services:
    sunshine-svc:
      loadBalancer:
        servers:
          - address: "192.168.1.2:47990"
```
</details>

### screengrab of Firefox when this happens (Chrome is same)
![image](https://user-images.githubusercontent.com/692914/232194233-53302915-e992-4d52-ba17-941c3aa7e8cf.png)

### Host Operating System

Windows

### Operating System Version

Windows 11 Pro 21H2 22000.1817

### Architecture

64 bit

### Sunshine commit or version

Version 0.19.1.010440dbd3e0e89e2dd891f0179d126745fa3460

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GTX 1080

### GPU Driver/Mesa Version

528.24

### Config

```Shell
cert = /Users/NAME/personal/apps/sunshine/cert/cert.crt
pkey = /Users/NAME/personal/apps/sunshine/cert/key.key
```

### Relevant log output

```shell
none
```
