### ISSUE TITLE
Struggling to get Docker start up

### ISSUE THREAD

**Issue by HarryAnkers** [LizardByte/Sunshine#2050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I'm guessing I am doing something incorrectly with the users of setting this up with docker. But when running docker compose I'm getting the follow error logs below.

I am trying do this with this docker compose:

```
version: '3'
name: "sunshine"
services:
  sunshine:
    image: lizardbyte/sunshine:nightly-ubuntu-22.04
    container_name: sunshine
    restart: unless-stopped
    volumes:
      - /home/harryankers/Services/Sunshine/config:/config
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    ports:
      - "47984-47990:47984-47990/tcp"
      - "48010:48010"
      - "47998-48000:47998-48000/udp"
```

I am running this with docker desktop so I wasn't sure if the puid and pgid mapping of that was messing this up.

### Expected Behavior

Expect the image to run

### Additional Context

No, got it to work with the AppImage but cant with docker.

### Host Operating System

Docker

### Operating System Version

Pop!_OS 22.04 LTS

### Architecture

64 bit

### Sunshine commit or version

e7e584d23041

### Package

Linux - Docker

### GPU Type

Nvidia

### GPU Model

3060 ti founders

### GPU Driver/Mesa Version

545.29.06

### Config

```Shell
av1_mode = 1
key_rightalt_to_key_win = enabled
```

### Relevant log output

```shell
sunshine exited with code 0
sunshine  | 2024-01-20T17:49:48.526192621Z [2024-01-20 17:49:48.526071] [0x00007f135db45000] [info]    Failed to apply config: filesystem error: cannot copy file: Permission denied [/usr/share/sunshine/apps.json] [/home/lizard/.config/sunshine/apps.json]
2024-01-20 17:49:48 sunshine  | [2024-01-20 17:49:48.849862] [0x00007efc784e3000] [info]    Failed to apply config: filesystem error: cannot copy file: Permission denied [/usr/share/sunshine/apps.json] [/home/lizard/.config/sunshine/apps.json]
```
