### ISSUE TITLE
CSS Content type headers are causing styles not to load when using a reverse proxy

### ISSUE THREAD

**Issue by zastrixarundell** [LizardByte/Sunshine#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

When accessing sunshine on localhost everything works fine. But when you try to use a reverse proxy like Caddy the content won't load how it should. 

The server will show that the header type for the CSS content is `text/plain` rather than `text/css`.

![image](https://user-images.githubusercontent.com/30195425/216686512-84685444-43dc-436b-8f91-c8620243f8a2.png)

### Expected Behavior

The page should look normally without any issue on it's end:

![image](https://user-images.githubusercontent.com/30195425/216686738-329b72b4-04ec-48fe-b7cf-1bd96fde1097.png)

### Additional Context

Setting the Caddyfile to catch all `*.css` files and forcing the content-type fixes the issue:

```
sunshine.localhost {
        @css path *.css
        header @css Content-Type text/css

        reverse_proxy localhost:47990 {
                transport http {
                      tls_insecure_skip_verify
                }
        }
}
```

### Host Operating System

Linux

### Operating System Version

Fedora 37

### Architecture

64 bit

### Sunshine commit or version

nigthly

### Package

Linux - flatpak

### GPU Type

Nvidia

### GPU Model

RTX 2070

### GPU Driver/Mesa Version

525.85.05

### Capture Method (Linux Only)

KMS

**Comment by zastrixarundell** [comment]
Can verify that the issue is not present anymore on nightly.

New setup works fine without any content type issues:
```
sunshine.localhost {
        reverse_proxy localhost:47990 {
                transport http {
                      tls_insecure_skip_verify
                }
        }
}
```

**Comment by kurac338** [comment]
Can confirm v0.18.2+ fixes the issue.

The following Traefik dynamic config works:

sunshine.yml
``` yml
---
http:
  routers:
    sunshine:
      service: sunshine-pc
      rule: "Host(`sunshine.<YOUR_DOMAIN>`)"
      entryPoints:
        - webSecure
      tls:
        certResolver: letsEncrypt
  services:
    sunshine-pc:
      loadBalancer:
        ## NOTE: Disables SSL certificate validation between Traefik and the backend
        serversTransport: disable-ssl@file
        servers:
          - url: "https://192.168.1.100:47990/"
```

disable-ssl.yml
``` yml
---
# Disables SSL certificate validation between Traefik and the backends
http:
  serversTransports:
    disable-ssl:
      insecureSkipVerify: true
```
