### ISSUE TITLE
can’t start from docker 

### ISSUE THREAD

**Issue by fulln** [LizardByte/Sunshine#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

i create a docker-compose.yml like this
```yml
version: '3'
services:
  sunshine:
    image: lizardbyte/sunshine:nightly-ubuntu-22.04
    container_name: sunshine
    restart: unless-stopped
    volumes:
      - ./config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - "47984-47990:47984-47990/tcp"
      - "48010:48010"
      - "47998-48000:47998-48000/udp"                                     
``` 

but when i stared it with `docker-compose up -d`,its failed to start and report error 

and my docker build on wsl2 

### Host Operating System

Docker

### Operating System Version

windows11 wsl2 Ubuntu 20.04.4

### Architecture

64 bit

### Sunshine commit or version

nightly-ubuntu-22.04

### Package

Linux - Docker

### GPU Type

AMD

### GPU Model

RTX6750

### GPU Driver/Mesa Version

22.11.2

### Relevant log output

```Shell
[2023:02:19:15:35:34]: Error: Couldn't find any of the following libraries: [libgbm.so.1, libgbm.so]
[2023:02:19:15:35:34]: Error: Couldn't load cuda: -1
[2023:02:19:15:35:34]: Warning: Couldn't find /dev/dri, kmsgrab won't be enabled
[2023:02:19:15:35:34]: Warning: libgbm not initialized
Cannot load libcuda.so.1
Cannot load libcuda.so.1
Cannot load libcuda.so.1
```
